req_lev:
  - M
  - HR
  - R
  - O
sample_type:
  - Water
assay_type: metabarcoding
project_id: my-project-id
assay_name:
  - ssu16sv4v5-parada
  - ssu18sv9-amaralzettler
projectMetadata_user:
  # - user_defined_project_term_1
  # - user_defined_project_term_2
sampleMetadata_user:
  # - user_defined_sample_term_1
  # - user_defined_sample_term_2
experimentRunMetadata_user:
  # - user_defined_experiment_run_term_1
  # - user_defined_experiment_run_term_2
