req_lev:
  - M
  - HR
  - R
  - O
sample_type:
  - Water
assay_type: metabarcoding
project_id: example_project_id
assay_name:
  - Bacteria-16S-V4V5-Parada
  - Eukarya-18S-V9-Lane-Medlin
projectMetadata_user:
  # - user_defined_project_term_1
  # - user_defined_project_term_2
sampleMetadata_user:
  # - user_defined_sample_term_1
  # - user_defined_sample_term_2
experimentRunMetadata_user:
  # - user_defined_experiment_run_term_1
  # - user_defined_experiment_run_term_2
